'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AttendanceAnalytics

    '''<summary>
    '''rptLateComers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptLateComers As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptOvertime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOvertime As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''hdnDailyTrendData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDailyTrendData As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnStatusDistributionData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStatusDistributionData As Global.System.Web.UI.WebControls.HiddenField
End Class
