'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Attendance

    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''ContentMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentMain As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''hdnUserRoleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUserRoleID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlEmployeeManagerView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmployeeManagerView As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''liTeamTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTeamTab As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptMyAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMyAttendance As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoMyAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoMyAttendance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRegDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRegPunchIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegPunchIn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRegPunchOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegPunchOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRegReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitRegularization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitRegularization As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblRegMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptTeamRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTeamRequests As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoTeamRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTeamRequests As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAdminView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdminView As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnAddAdminRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAdminRecord As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptAllAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAllAttendance As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoAllAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoAllAttendance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnAdminLogID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAdminLogID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtAdminEmployeeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminEmployeeID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdminLogDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminLogDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdminPunchInTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminPunchInTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdminPunchOutTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdminPunchOutTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAdminStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAdminStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAdminModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminModalMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSaveAdminRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAdminRecord As Global.System.Web.UI.WebControls.Button
End Class