'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard

    '''<summary>
    '''pnlTotalEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTotalEmployees As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litTotalEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTotalEmployees As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlPresentToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPresentToday As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litPresentToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPresentToday As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlOnLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOnLeave As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litOnLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOnLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlUpcomingHolidays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUpcomingHolidays As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litUpcomingHolidays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUpcomingHolidays As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlUpcomingBirthdays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUpcomingBirthdays As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litUpcomingBirthdays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUpcomingBirthdays As Global.System.Web.UI.WebControls.Literal
End Class
