'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LeaveManagement

    '''<summary>
    '''liTeamApprovalsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTeamApprovalsTab As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCasualLeaveBalanceUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCasualLeaveBalanceUsed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCasualLeaveTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCasualLeaveTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSickLeaveBalanceUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSickLeaveBalanceUsed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSickLeaveTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSickLeaveTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaidLeaveBalanceUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaidLeaveBalanceUsed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaidLeaveTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaidLeaveTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptCompanyHolidays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCompanyHolidays As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoCompanyHolidays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoCompanyHolidays As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptUpcomingMyLeaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUpcomingMyLeaves As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoUpcomingMyLeaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoUpcomingMyLeaves As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLeaveType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLeaveType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlReportToManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportToManager As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitLeave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblLeaveMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeaveMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptMyLeaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMyLeaves As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoMyLeavesHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoMyLeavesHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptTeamLeaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTeamLeaves As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoTeamLeaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTeamLeaves As Global.System.Web.UI.WebControls.Label
End Class
