'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PeerFeedback

    '''<summary>
    '''rptRequestsForMe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptRequestsForMe As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoRequestsForMe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoRequestsForMe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnShowRequestModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowRequestModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptRequestsSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptRequestsSent As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoRequestsSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoRequestsSent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlForEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlForEmployee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cblFromEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblFromEmployees As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''btnSendRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendRequests As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblProvideFeedbackFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProvideFeedbackFor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnPeerFeedbackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPeerFeedbackID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtFeedbackComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeedbackComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitFeedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitFeedback As Global.System.Web.UI.WebControls.Button
End Class
