'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Performance

    '''<summary>
    '''pnlMyReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMyReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCycleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCycleName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmployeeComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployeeComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rptMyKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMyKPIs As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoMyKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoMyKPIs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtManagerComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManagerComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblManagerRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblManagerRating As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnReviewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnReviewID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnSubmitToManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitToManager As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlTeamView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTeamView As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptTeamReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTeamReviews As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoTeamReviews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTeamReviews As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCycleManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCycleManagement As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptCycles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCycles As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''txtCycleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCycleName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCycleStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCycleStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCycleEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCycleEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddCycle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCycle As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCycleMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCycleMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAssignKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssignKPIs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAssignKpiCycleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignKpiCycleName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlEmployeesForKPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmployeesForKPI As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlAvailableKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAvailableKPIs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cblMasterKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblMasterKPIs As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''btnAssignSelectedKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssignSelectedKPIs As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlAssignedKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssignedKPIs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptAssignedKPIs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAssignedKPIs As Global.System.Web.UI.WebControls.Repeater
End Class
