'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PerformanceAnalytics

    '''<summary>
    '''litAverageRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAverageRating As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompletionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompletionRate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litActiveCycleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litActiveCycleName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rptTopPerformers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTopPerformers As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptAttritionRisks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAttritionRisks As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''hdnChartData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnChartData As Global.System.Web.UI.WebControls.HiddenField
End Class
