'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Recruitment

    '''<summary>
    '''btnShowJobModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowJobModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptJobVacancies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptJobVacancies As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoJobs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlJobFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobFilter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnClearFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptCandidates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCandidates As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoCandidates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoCandidates As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAvailableJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAvailableJobs As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtApplicantName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplicantName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApplicantEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplicantEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApplicantPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplicantPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApplicantAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplicantAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLinkedInProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkedInProfile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDesiredSalary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesiredSalary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEarliestStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEarliestStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fuResume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuResume As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''fuCoverLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuCoverLetter As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ddlApplicationSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlApplicationSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSubmitApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitApplication As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblApplicationFormMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplicationFormMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnCurrentJobID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCurrentJobID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtJobTitleModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobTitleModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDepartmentModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartmentModal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlLocationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocationType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSpecificLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecificLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlEmploymentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmploymentType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlExperienceLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExperienceLevel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEducationLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEducationLevel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtMinSalary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinSalary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMaxSalary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxSalary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBenefitsDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBenefitsDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKeyResponsibilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKeyResponsibilities As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRequiredSkills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequiredSkills As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJobDescriptionModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobDescriptionModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApplicationDeadlineModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplicationDeadlineModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlHiringManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHiringManager As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNumberOfPositions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumberOfPositions As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlJobStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblJobModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobModalMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSaveJobOpening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveJobOpening As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnCandidateID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCandidateID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCandidateJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCandidateJobTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDesiredSalary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesiredSalary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEarliestStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEarliestStart As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlLinkedIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlLinkedIn As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblApplicationSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplicationSource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppliedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppliedOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlResume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlResume As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlCoverLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlCoverLetter As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ddlCandidateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCandidateStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtInterviewNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInterviewNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAssessmentScores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssessmentScores As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkIDProof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIDProof As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAddressProof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddressProof As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEduCerts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEduCerts As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPrevEmpLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrevEmpLetter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkBackgroundCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBackgroundCheck As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkReferenceCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReferenceCheck As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtHRRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHRRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCandidateModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCandidateModalMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnUpdateCandidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateCandidate As Global.System.Web.UI.WebControls.Button
End Class
