'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Resignation

    '''<summary>
    '''hdnUserRoleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUserRoleID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''liManageResignationsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liManageResignationsTab As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlResignationForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResignationForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblEmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentJobTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateOfJoining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateOfJoining As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTenure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTenure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResignationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResignationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProposedLastWorkingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProposedLastWorkingDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtResignationReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResignationReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitResignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitResignation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblResignationMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResignationMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlResignationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResignationStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCurrentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmittedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmittedOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litResignationReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litResignationReason As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblRequestedLastWorkingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestedLastWorkingDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApprovedLastWorkingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprovedLastWorkingDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoticePeriodLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoticePeriodLeft As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnWithdrawResignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWithdrawResignation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptPendingResignations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPendingResignations As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoPendingResignations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoPendingResignations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptOtherResignations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOtherResignations As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNoOtherResignations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoOtherResignations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModalEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalEmpName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnResignationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnResignationID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblModalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModalSubmittedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalSubmittedOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litModalReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litModalReason As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblModalRequestedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalRequestedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtApprovedLastWorkingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApprovedLastWorkingDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNoticePeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoticePeriod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUpdateStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtInternalNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInternalNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSaveResignationDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveResignationDetails As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnModalApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalApprove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnModalReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalReject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnModalCreateVacancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalCreateVacancy As Global.System.Web.UI.WebControls.Button
End Class
